package com.ascend.mavlab.feature.onboarding.generated

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

// AUTO-GENERATED by tools/pen2compose from a Pencil (.pen) node tree. Do not hand-edit;
// re-run the converter and polish gradients/canvas/shadows (flagged with // TODO).

@Composable
fun AdvancedInputsGenerated(modifier: Modifier = Modifier) {
    Column(modifier = Modifier.width(312.dp).background(Color(0xFF141B2D), RoundedCornerShape(16.dp)).border(1.dp, Color(0xFF1E2740), RoundedCornerShape(16.dp)).padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {  // Advanced Inputs
        Text(text = "Motor failure", fontSize = 14.sp, color = Color(0xFFCBD5E1))
        Column(modifier = Modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(8.dp)) {  // MotorGrid
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {  // MRow1
                Row(modifier = Modifier.border(1.5.dp, Color(0xFF1E2740), RoundedCornerShape(999.dp)).padding(horizontal = 12.dp, vertical = 7.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {  // Motor 1
                    Text(text = "Motor 1", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = Color(0xFF94A3B8))
                }
                Row(modifier = Modifier.background(Color(0xFF1E3A5F), RoundedCornerShape(999.dp)).padding(horizontal = 12.dp, vertical = 7.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {  // Motor 2
                    Icon(Icons.Default.Check, contentDescription = null, tint = Color(0xFF60A5FA), modifier = Modifier.size(13.dp))
                    Text(text = "Motor 2", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = Color(0xFFE2E8F0))
                }
            }
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {  // MRow2
                Row(modifier = Modifier.border(1.5.dp, Color(0xFF1E2740), RoundedCornerShape(999.dp)).padding(horizontal = 12.dp, vertical = 7.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {  // Motor 3
                    Text(text = "Motor 3", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = Color(0xFF94A3B8))
                }
                Row(modifier = Modifier.border(1.5.dp, Color(0xFF1E2740), RoundedCornerShape(999.dp)).padding(horizontal = 12.dp, vertical = 7.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {  // Motor 4
                    Text(text = "Motor 4", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = Color(0xFF94A3B8))
                }
            }
        }
        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {  // GpsRow
            Text(text = "GPS available", fontSize = 14.sp, color = Color(0xFFCBD5E1))
            Box(modifier = Modifier.width(44.dp).height(24.dp).background(Color(0xFF1E2740), RoundedCornerShape(999.dp))) {  // Switch
                Box(Modifier.width(18.dp).height(18.dp).offset(3.dp, 3.dp).clip(CircleShape).background(Color(0xFF94A3B8)))
            }
        }
        Text(text = "Wind preset", fontSize = 14.sp, color = Color(0xFFCBD5E1))
        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {  // WindRow
            Row(modifier = Modifier.border(1.5.dp, Color(0xFF1E2740), RoundedCornerShape(999.dp)).padding(horizontal = 12.dp, vertical = 7.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {  // None
                Text(text = "None", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = Color(0xFF94A3B8))
            }
            Row(modifier = Modifier.border(1.5.dp, Color(0xFF1E2740), RoundedCornerShape(999.dp)).padding(horizontal = 12.dp, vertical = 7.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {  // Light
                Text(text = "Light", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = Color(0xFF94A3B8))
            }
            Row(modifier = Modifier.background(Color(0xFF1E3A5F), RoundedCornerShape(999.dp)).padding(horizontal = 12.dp, vertical = 7.dp), horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {  // Strong
                Icon(Icons.Default.Check, contentDescription = null, tint = Color(0xFF60A5FA), modifier = Modifier.size(13.dp))
                Text(text = "Strong", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = Color(0xFFE2E8F0))
            }
        }
        Row(modifier = Modifier.fillMaxWidth().height(44.dp).border(1.5.dp, Color(0xFF1E2740), RoundedCornerShape(999.dp)), horizontalArrangement = Arrangement.Center, verticalAlignment = Alignment.CenterVertically) {  // Reset
            Text(text = "Reset perturbations", fontSize = 14.sp, color = Color(0xFFCBD5E1))
        }
    }
}
