package com.ascend.mavlab.feature.onboarding.generated

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

// AUTO-GENERATED by tools/pen2compose from a Pencil (.pen) node tree. Do not hand-edit;
// re-run the converter and polish gradients/canvas/shadows (flagged with // TODO).

@Composable
fun SurfaceGalleryGenerated(modifier: Modifier = Modifier) {
    Column(modifier = Modifier.fillMaxWidth().fillMaxHeight(), verticalArrangement = Arrangement.Center) {  // Scene 3
        Column(modifier = Modifier.width(312.dp), verticalArrangement = Arrangement.spacedBy(18.dp)) {  // GalWrap
            Box(modifier = Modifier.fillMaxWidth().height(200.dp)) {  // GalleryClip
                Row(modifier = Modifier.offset(0.dp, 2.dp), horizontalArrangement = Arrangement.spacedBy(12.dp)) {  // Gallery
                    Column(modifier = Modifier.width(140.dp).height(196.dp).background(Color(0xFF141B2D), RoundedCornerShape(20.dp)).border(1.dp, Color(0xFF1E2740), RoundedCornerShape(20.dp)).padding(16.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) {  // Cockpit Card
                        Row(modifier = Modifier.width(46.dp).height(46.dp).background(Color(0x1F60A5FA), RoundedCornerShape(13.dp)), horizontalArrangement = Arrangement.Center, verticalAlignment = Alignment.CenterVertically) {  // IconBox
                            Icon(Icons.Default.Analytics, contentDescription = null, tint = Color(0xFF60A5FA), modifier = Modifier.size(24.dp))
                        }
                        Text(text = "Cockpit", fontSize = 17.sp, fontWeight = FontWeight.SemiBold, color = Color(0xFFE2E8F0))
                        Text(text = "Telemetry, safety state, mission awareness", fontSize = 13.sp, fontWeight = FontWeight.Normal, color = Color(0xFF94A3B8), modifier = Modifier.fillMaxWidth())
                    }
                    Column(modifier = Modifier.width(140.dp).height(196.dp).background(Color(0xFF141B2D), RoundedCornerShape(20.dp)).border(1.dp, Color(0xFF1E2740), RoundedCornerShape(20.dp)).padding(16.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) {  // Controller Card
                        Row(modifier = Modifier.width(46.dp).height(46.dp).background(Color(0x1F60A5FA), RoundedCornerShape(13.dp)), horizontalArrangement = Arrangement.Center, verticalAlignment = Alignment.CenterVertically) {  // IconBox
                            Icon(Icons.Default.ControlCamera, contentDescription = null, tint = Color(0xFF60A5FA), modifier = Modifier.size(24.dp))
                        }
                        Text(text = "Controller", fontSize = 17.sp, fontWeight = FontWeight.SemiBold, color = Color(0xFFE2E8F0))
                        Text(text = "Phone sensors, manual input, quick test", fontSize = 13.sp, fontWeight = FontWeight.Normal, color = Color(0xFF94A3B8), modifier = Modifier.fillMaxWidth())
                    }
                    Column(modifier = Modifier.width(140.dp).height(196.dp).background(Color(0xFF141B2D), RoundedCornerShape(20.dp)).border(1.dp, Color(0xFF1E2740), RoundedCornerShape(20.dp)).padding(16.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) {  // SIM Card
                        Row(modifier = Modifier.width(46.dp).height(46.dp).background(Color(0x1F34D399), RoundedCornerShape(13.dp)), horizontalArrangement = Arrangement.Center, verticalAlignment = Alignment.CenterVertically) {  // IconBox
                            Icon(Icons.Default.Height, contentDescription = null, tint = Color(0xFF34D399), modifier = Modifier.size(24.dp))
                        }
                        Text(text = "SIM", fontSize = 17.sp, fontWeight = FontWeight.SemiBold, color = Color(0xFFE2E8F0))
                        Text(text = "3D attitude, altitude, motors", fontSize = 13.sp, fontWeight = FontWeight.Normal, color = Color(0xFF94A3B8), modifier = Modifier.fillMaxWidth())
                    }
                    Column(modifier = Modifier.width(140.dp).height(196.dp).background(Color(0xFF141B2D), RoundedCornerShape(20.dp)).border(1.dp, Color(0xFF1E2740), RoundedCornerShape(20.dp)).padding(16.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) {  // Mission Card
                        Row(modifier = Modifier.width(46.dp).height(46.dp).background(Color(0x1FFBBF24), RoundedCornerShape(13.dp)), horizontalArrangement = Arrangement.Center, verticalAlignment = Alignment.CenterVertically) {  // IconBox
                            Icon(Icons.Default.Route, contentDescription = null, tint = Color(0xFFFBBF24), modifier = Modifier.size(24.dp))
                        }
                        Text(text = "Mission", fontSize = 17.sp, fontWeight = FontWeight.SemiBold, color = Color(0xFFE2E8F0))
                        Text(text = "QGC upload, waypoints, AUTO", fontSize = 13.sp, fontWeight = FontWeight.Normal, color = Color(0xFF94A3B8), modifier = Modifier.fillMaxWidth())
                    }
                    Column(modifier = Modifier.width(140.dp).height(196.dp).background(Color(0xFF141B2D), RoundedCornerShape(20.dp)).border(1.dp, Color(0xFF1E2740), RoundedCornerShape(20.dp)).padding(16.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) {  // Ops Card
                        Row(modifier = Modifier.width(46.dp).height(46.dp).background(Color(0x1F94A3B8), RoundedCornerShape(13.dp)), horizontalArrangement = Arrangement.Center, verticalAlignment = Alignment.CenterVertically) {  // IconBox
                            Icon(Icons.Default.Settings, contentDescription = null, tint = Color(0xFF94A3B8), modifier = Modifier.size(24.dp))
                        }
                        Text(text = "Ops", fontSize = 17.sp, fontWeight = FontWeight.SemiBold, color = Color(0xFFE2E8F0))
                        Text(text = "MAVLink status, logs, export", fontSize = 13.sp, fontWeight = FontWeight.Normal, color = Color(0xFF94A3B8), modifier = Modifier.fillMaxWidth())
                    }
                }
            }
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center, verticalAlignment = Alignment.CenterVertically) {  // Dots
                Row(modifier = Modifier.width(20.dp).height(7.dp).background(Color(0xFF60A5FA), RoundedCornerShape(999.dp))) {}  // Dot1
                Row(modifier = Modifier.width(7.dp).height(7.dp).background(Color(0xFF1E2740), RoundedCornerShape(999.dp))) {}  // Dot2
                Row(modifier = Modifier.width(7.dp).height(7.dp).background(Color(0xFF1E2740), RoundedCornerShape(999.dp))) {}  // Dot3
                Row(modifier = Modifier.width(7.dp).height(7.dp).background(Color(0xFF1E2740), RoundedCornerShape(999.dp))) {}  // Dot4
                Row(modifier = Modifier.width(7.dp).height(7.dp).background(Color(0xFF1E2740), RoundedCornerShape(999.dp))) {}  // Dot5
            }
        }
    }
}
